Repository HenryBcit/SystemAdminLab, pull requests merged in 2019-09, with the labels that each got.

#4 added henry html
  henry.html
  index.html
Labels: bug, help wanted

#1 added Rocky
  Rocky.html
Labels: bug, duplicate

#10 added features to index
  index.html
Labels: enhancement
